### ISSUE TITLE
Null directory creation

### ISSUE THREAD

**Issue by baserrato** [snowmang1/scripts#8]
- New directory created name 'null' whenever running name piece of the aws script.
- New directory contains serv-setup.sh
- Possibly a scp issue since naming has us scp the setup script onto the instance.

**Comment by snowmang1** [comment]
I believe this is due to the fact that the `scp` function is uploading a directory, and if that address is not found to be a valid IP or destination it 'can' just upload it to its own dir

**Comment by snowmang1** [comment]
This issue was due to scp having an incorrect name space to connect with
